# Generated by Django 4.2.3 on 2023-09-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'MARKA',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('image', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FİRMA',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stock', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uptaded', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_b', to='stokApp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_c', to='stokApp.category')),
            ],
            options={
                'verbose_name_plural': 'ÜRÜN',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('price_total', models.DecimalField(decimal_places=8, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_b', to='stokApp.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_p', to='stokApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SATIŞ',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitiy', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=3)),
                ('price_total', models.DecimalField(decimal_places=3, max_digits=3)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpurchases', to='stokApp.brand')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpurchases', to='stokApp.firm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_purchases', to='stokApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ALIŞVERİŞ',
            },
        ),
    ]
