# Generated by Django 4.2.3 on 2023-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'KATEGORİ'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uptaded',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
