# Generated by Django 4.2.3 on 2023-09-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokApp', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='firm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='quantity',
            new_name='quantitiy',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='price_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
