# Generated by Django 4.2.3 on 2023-09-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokApp', '0005_alter_brand_image_alter_firm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='image/'),
        ),
    ]
