# Generated by Django 4.2.3 on 2023-09-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokApp', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='sales',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='image/'),
        ),
    ]
